add dynamic pages for biscuit
techtee-ltd/biscuit-recruitment-website pull request #19
Opened 2024-07-12 13:05 UTC by tobi-ajala

2024-07-12 13:06 UTC, techtee-dev approved these changes

2024-07-12 13:12 UTC, techtee-dev requested changes
This breaks deployment

2024-07-23 10:58 UTC, tobi-ajala commented
#### 📝 Changed routes:


| [**/our-story**](https://biscuit-recruitment-website-lviwos0tg-techtee.vercel.app/our-story) | [**/philosophy**](https://biscuit-recruitment-website-lviwos0tg-techtee.vercel.app/philosophy) |
|:-:|:-:|
|<a href="https://biscuit-recruitment-website-lviwos0tg-techtee.vercel.app/our-story"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/wBvlUDMxHgPmGAlSx2Q0TKTCsYW4iV30ZVHuVXZ8QFCZfB4OnkT8ILK6OiJv-QJjSQJOUXOrBt67kpHSJ2MFxQ.png&w=600" alt="Screenshot of /our-story" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/MaeCJZg5lqaugxZvhn2k7gyqj1Q0psYwRvn765PF5g2s61geUS3O6W6HO0SdgNBApxgaUAktreVop3Sk6IkWVA.png">(view full size)</a> |<a href="https://biscuit-recruitment-website-lviwos0tg-techtee.vercel.app/philosophy"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/ghs5nQBUK7TYKTV2yII18R7Tmojx2h3IjB27QRlW-_qvd8id1BuI-Kd_cDK2_kCcmAYfmPvpGVf9U6M3hLcORw.png&w=600" alt="Screenshot of /philosophy" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/LMAnSkbMg4NOfACn48pK-KUg35OfciKGJFzk7J4ehrSjJiwIbr5loPq-M61pkS_KEMFB_Za354VGhe6axpvWcA.png">(view full size)</a> |







Commit 0e26869d71ce825e388778f2c64a2aecdc918861 (https://biscuit-recruitment-website-lviwos0tg-techtee.vercel.app).

2024-07-29 16:34 UTC, techtee-dev approved these changes

2024-07-29 16:34 UTC, merged